import { Inter } from "next/font/google";
import StoreProvider from "./StoreProvider";
import "./globals.css";
import Header from "./ui/header/Header";
import Footer from "./ui/footer/Footer";
import Cart from "./ui/cart/Cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <html className="bg-[#000000]" lang="en">
          <body className={`${inter.className} body`}>
            <Header/>
            {children}
            <Footer/>
          </body>
      </html>
    </StoreProvider>
  );
}